name: calcular-edad-y-etapa-de-la-vida

on:
  workflow_dispatch:
    inputs:
      dia:
        description: 'Día de nacimiento'
        required: true
      mes:
        description: 'Mes de nacimiento'
        required: true
      anio:
        description: 'Año de nacimiento'
        required: true

env:
  # Estas variables deben estar también creadas en GitHub repo > Settings > Variables
  LIM_NINEZ: 13
  LIM_ADOLESCENCIA: 17
  LIM_ADULTO_JOVEN: 35
  LIM_ADULTO: 64

jobs:
  calcular-edad:
    name: Calcular edad
    runs-on: ubuntu-latest
    outputs:
      edad_actual: ${{ steps.calcular.outputs.edad }}
      edad_anios: ${{ steps.calcular.outputs.anios }}

    steps:
      - name: Calcular edad actual
        id: calcular
        run: |
          DIA="${{ inputs.dia }}"
          MES="${{ inputs.mes }}"
          ANIO="${{ inputs.anio }}"

          FECHA_ACTUAL=$(date +%Y-%m-%d)
          ANIO_ACTUAL=$(date +%Y)
          MES_ACTUAL=$(date +%m)
          DIA_ACTUAL=$(date +%d)

          ANOS=$((ANIO_ACTUAL - ANIO))
          MESES=$((MES_ACTUAL - MES))
          DIAS=$((DIA_ACTUAL - DIA))

          if [ "$DIAS" -lt 0 ]; then
            MESES=$((MESES - 1))
            DIAS=$((DIAS + 30))  # Aproximado
          fi

          if [ "$MESES" -lt 0 ]; then
            ANOS=$((ANOS - 1))
            MESES=$((MESES + 12))
          fi

          EDAD_FORMATO="${ANOS} años, ${MESES} meses, ${DIAS} días"

          echo "Edad calculada: $EDAD_FORMATO"
          echo "edad=$EDAD_FORMATO" >> "$GITHUB_OUTPUT"
          echo "anios=$ANOS" >> "$GITHUB_OUTPUT"

  clasificar-etapa:
    name: Clasificar etapa
    runs-on: ubuntu-latest
    needs: calcular-edad

    steps:
      - name: Clasificar etapa de la vida
        run: |
          EDAD="${{ needs.calcular-edad.outputs.edad_actual }}"
          ANOS="${{ needs.calcular-edad.outputs.anios }}"

          echo "Edad recibida: $EDAD"

          if [ "$ANOS" -le "${{ vars.LIM_NINEZ }}" ]; then
            echo " Etapa de vida: Niñez (0-13 años)"
          elif [ "$ANOS" -le "${{ vars.LIM_ADOLESCENCIA }}" ]; then
            echo " Etapa de vida: Adolescencia (14-17 años)"
          elif [ "$ANOS" -le "${{ vars.LIM_ADULTO_JOVEN }}" ]; then
            echo " Etapa de vida: Adulto joven (18-35 años)"
          elif [ "$ANOS" -le "${{ vars.LIM_ADULTO }}" ]; then
            echo " Etapa de vida: Adulto (36-64 años)"
          else
            echo " Etapa de vida: Tercera edad (65+ años)"
          fi