#Crear un pipeline que reciba como inputs el año mes y día de nacimiento 
#y con base a esos datos calcule la edad actual de la persona (Formato: 27 años, 9 meses, 17 días) 
#y luego use esa edad para clasificar a la persona en la etapa de la vida que aplique.

#La ejecución fue exitosa en Github actions
#El workflow tiene un nombre
#El workflow usa el runner de ubuntu-latest
#El workflow usa el evento workflow_dispatch
#El workflow tiene tres inputs, día, mes y año de nacimiento
#El workflow usa las variables de entorno del repositorio (Rangos de edades)
#El workflow usa dos jobs y un step en cada job
#Los steps y los jobs tienen un nombre
#El workflow es claro, entendible y efectivo
#El primer job debe tener un output el cual se debe usar en el segundo job
#Variables de repositorio:

#LIM_NINEZ = 13
#LIM_ADOLESCENCIA = 17
#LIM_ADULTO_JOVEN = 35
#LIM_ADULTO = 64

name: etapa-de-la-vida

on:
 push:
  branches:
    - master
    - feature/ecosistemapipeline
    
  workflow_dispatch:
    inputs:
      dia:
        description: 'Día de nacimiento'
        required: true
        type: string
      mes:
        description: 'Mes de nacimiento'
        required: true
        type: string
      anio:
        description: 'Año de nacimiento'
        required: true
        type: string

env:
  LIM_NINEZ: 13
  LIM_ADOLESCENCIA: 17
  LIM_ADULTO_JOVEN: 35
  LIM_ADULTO: 64

jobs:
  calculo_edad:
    name: Calcular edad exacta
    runs-on: ubuntu-latest
    outputs:
      edad_formato: ${{ steps.calcular.outputs.edad_formato }}
      edad_años: ${{ steps.calcular.outputs.edad_años }}
    steps:
      - name: Calcular edad
        id: calcular
        run: |
          DIA_NAC=${{ inputs.dia }}
          MES_NAC=${{ inputs.mes }}
          AÑO_NAC=${{ inputs.anio }}

          FECHA_ACTUAL=$(date +%Y-%m-%d)
          AÑO_ACTUAL=$(date +%Y)
          MES_ACTUAL=$(date +%m)
          DIA_ACTUAL=$(date +%d)

          EDAD_AÑOS=$((AÑOS_ACTUAL - AÑOS_NAC))
          EDAD_MESES=$((MES_ACTUAL - MES_NAC))
          EDAD_DIAS=$((DIA_ACTUAL - DIA_NAC))

          if [ $EDAD_DIAS -lt 0 ]; then
            EDAD_MESES=$((EDAD_MESES - 1))
            EDAD_DIAS=$((EDAD_DIAS + 30))
          fi

          if [ $EDAD_MESES -lt 0 ]; then
            EDAD_AÑOS=$((EDAD_AÑOS - 1))
            EDAD_MESES=$((EDAD_MESES + 12))
          fi

          FORMATO="${EDAD_AÑOS} años, ${EDAD_MESES} meses, ${EDAD_DIAS} días"
          echo "Edad calculada: $FORMATO"

          echo "edad_formato=$FORMATO" >> "$GITHUB_OUTPUT"
          echo "edad_años=$EDAD_AÑOS" >> "$GITHUB_OUTPUT"

  clasificacion:
    name: Clasificar etapa de vida
    runs-on: ubuntu-latest
    needs: calculo_edad
    steps:
      - name: Determinar etapa
        run: |
          EDAD=${{ needs.calculo_edad.outputs.edad_años }}
          FORMATO="${{ needs.calculo_edad.outputs.edad_formato }}"
          echo "Edad recibida: $FORMATO"

          if [ "$EDAD" -le $LIM_NINEZ ]; then
            ETAPA="Niñez"
          elif [ "$EDAD" -le $LIM_ADOLESCENCIA ]; then
            ETAPA="Adolescencia"
          elif [ "$EDAD" -le $LIM_ADULTO_JOVEN ]; then
            ETAPA="Adulto joven"
          elif [ "$EDAD" -le $LIM_ADULTO ]; then
            ETAPA="Adulto"
          else
            ETAPA="Adulto mayor"
          fi

          echo "✅ Etapa de la vida: $ETAPA"