name: linea-de-tiempo

on:
  workflow_dispatch:
    inputs:
      mes:
        description: 'Mes del acontecimiento'
        required: true
      dia:
        description: 'Día del acontecimiento'
        required: true

jobs:
  descargar-informacion-acontecimiento:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar variables
        run: |
          echo "MONTH=${{ github.event.inputs.mes }}" >> $GITHUB_ENV
          echo "DAY=${{ github.event.inputs.dia }}" >> $GITHUB_ENV
          echo "LANGUAGE=${{ vars.LANG }}" >> $GITHUB_ENV

      # Cache para la respuesta del API
      - name: Cache respuesta API
        id: cache_api
        uses: actions/cache@v3
        with:
          path: cache_apis
          key: linea-de-tiempo-${{ env.LANGUAGE }}-${{ env.DAY }}-${{ env.MONTH }}

      - name: Consumir API de Línea de Tiempo
        id: consumir_api
        run: |
          # Verifica si ya existe cache
          if [ -f cache_apis/response.json ]; then
            echo "Usando cache existente"
            cp cache_apis/response.json acontecimiento.html
          else
            echo "Cache no encontrado, consultando API..."
            RESPONSE=$(curl --silent --location "https://api.wikimedia.org/feed/v1/wikipedia/$LANGUAGE/onthisday/all/$MONTH/$DAY")
          
            # Guardar JSON en cache
            mkdir -p cache_apis
            echo "$RESPONSE" > cache_apis/response.json

            # Crear archivo HTML para PDF
            echo "<html><body><pre>$RESPONSE</pre></body></html>" > acontecimiento.html
          fi

      - name: Convertir HTML a PDF
        uses: ntdesmond/html2pdf-action@v1
        with:
          path: ./acontecimiento.html
          output: ./acontecimiento.pdf
          options: |
            {"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}

      - name: Subir artefactos (HTML y PDF)
        uses: actions/upload-artifact@v4
        with:
          name: acontecimiento-${{ github.event.inputs.dia }}-${{ github.event.inputs.mes }}
          path: |
            acontecimiento.html
            acontecimiento.pdf
          retention-days: 1