name: linea-de-tiempo

on:
  workflow_dispatch:
    inputs:
      mes:
        description: 'Mes del acontecimiento'
        required: true
      dia:
        description: 'Día del acontecimiento'
        required: true

jobs:
  preparar-eventos:
    runs-on: ubuntu-latest
    outputs:
      eventos: ${{ steps.set_matrix.outputs.eventos }}
    steps:
      - name: Configurar variables
        run: |
          echo "MONTH=${{ github.event.inputs.mes }}" >> $GITHUB_ENV
          echo "DAY=${{ github.event.inputs.dia }}" >> $GITHUB_ENV
          echo "LANGUAGE=${{ vars.LANG }}" >> $GITHUB_ENV

      - name: Consumir API de Línea de Tiempo
        id: consumir_api
        run: |
          RESPONSE=$(curl --silent --location "https://api.wikimedia.org/feed/v1/wikipedia/$LANGUAGE/onthisday/all/$MONTH/$DAY")

          mkdir -p matrix
          echo "$RESPONSE" | jq -c --arg DAY "$DAY" --arg MONTH "$MONTH" \
            '.selected[] | {url: .pages[0].content_urls.desktop.page, title: .pages[0].title, day: $DAY, month: $MONTH}' \
            > matrix/eventos.json

      - name: Guardar eventos para matrix
        id: set_matrix
        run: |
          JSON=$(cat matrix/eventos.json | jq -s -c '.')
          echo "eventos=$JSON" >> $GITHUB_OUTPUT

  generar-pdfs:
    needs: preparar-eventos
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        evento: ${{ fromJSON(needs.preparar-eventos.outputs.eventos) }}
    steps:
      - name: Preparar nombre de archivo
        run: |
          SANITIZED_TITLE=$(echo "${{ matrix.evento.title }}" | tr ' ' '_' | tr -d '\"')
          FILE_NAME="${{ matrix.evento.month }}-${{ matrix.evento.day }}-${SANITIZED_TITLE}"
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV

      - name: Convertir URL a PDF
        uses: jasongitmail/url-to-pdf@v1
        with:
          url: ${{ matrix.evento.url }}
          output: ${{ env.FILE_NAME }}.pdf

      - name: Subir PDF como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE_NAME }}
          path: ${{ env.FILE_NAME }}.pdf
          retention-days: 1