#Buscar en el marketplace un action que convierte el siguiente texto en json 
#a un archivo con nombre archivo.json y que al final lo cargue como un artefacto

name: convertir-texto-a-json
on:
  push:
    branches:
      - feature/*

jobs:
  convertir-texto:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
          distribution: 'adopt'
          java-version: '17'
     - name: Convertir texto a JSON
       uses: devops-actions/json-to-file@v1.0.0
       with:
          json: '{"name": "pipelines","activity": 3,"module": 2,"isRequired": false}'
          filename: 'archivo.json'