#Crear un pipeline que sume dos numeros dados por variables de entorno en Github y
#que muestre un mensaje dependiendo de si el resultado de la suma mayor a 10 o menor/igual a 10.
 
#La ejecucion fue exitosa en Github actions
#El workflow tiene un nombre
#El workflow usa el runner de ubuntu-latest
#El workflow usa el evento push
#El workflow tiene en el desencadenador el filtro de rama para cualquier nombre que empiece por test/
#El workflow usa las variables de entorno del repositorio
#El workflow usa dos jobs y un step en cada job
#Los steps y los jobs tienen un nombre
#El workflow es claro, entendible y efectivo

name: suma-dos-numeros
on:
 push:
  branches:
    - feature/ecosistemapipeline
jobs:
  suma:
    runs-on: ubuntu-latest
    outputs:
      valorfinal: ${{ steps.sumar.outputs.total }}

    steps:
      - name: Sumar dos números
        id: sumar
        run: |
          NUM1=6
          NUM2=4
          RESULTADO=$((NUM1 + NUM2))
          echo "total=$RESULTADO" >> "$GITHUB_OUTPUT"
          echo "La suma de $NUM1 y $NUM2 es: $RESULTADO"

  validacion:
    runs-on: ubuntu-latest
    needs: suma
    steps:        
      - name: Comparación de resultados
        run: |
          echo "DEBUG: ${{ needs.suma.outputs.valorfinal }}"
          if [ ${{needs.suma.outputs.valorfinal}} -gt 10 ]; then
            echo "El resultado ${{needs.suma.outputs.valorfinal}} es mayor 10."
          else
            echo "El resultado ${{needs.suma.outputs.valorfinal}} es menor o igual a 10."
          fi
          

          
